-- Core Config
require "config.options"
require "config.plugin-init"
require "config.keymaps"
require "config.utils"
require "config.language_options"
require "config.treesitter"
require "config.languages"
require "config.debugging"
require "config.testing"
