require "config.options"
require "config.utils"
require "config.keymaps"
require "config.plugins"

require "config.navigation"
require "config.language_options"
require "config.treesitter"
require "config.autocomplete"
require "config.snippets"
require "config.lsp"
require "config.git"
require "config.startup_screen"
require "config.indentation_guidelines"
require "config.statusline"
require "config.learning"
